language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
install:
  - composer install
branches:
  only:
    - master
cache:
  directories:
  - vendor
  - node_modules
git:
  submodules: false
before_script:
  - "mysql -e 'create database angular_cms_test;'"
  - "cp ./.travis.database.yml ./config/database.yml"