database:
    driver: pdo_mysql
    user: cmsv4
    password: cmsv4
    dbname: cmsv4
    host: localhost
mail:
    CharSet: utf-8
    SMTPAuth: true
    Host: host
    Username: user
    Password: pass
    Port: 587
