database:
    driver: pdo_mysql
    username: cmsv4
    password: cmsv4
    dbname: cmsv4
    host: localhost

mail:
    char_set: utf-8
    host: 
    smtp_auth: true
    username: 
    password:
    port: 587