imports:
  - { resource: parameters.yml}

parameters:
    database_host: localhost
    database_port: 3306
    database_name: cmsv5
    database_user: cmsv5
    database_password: cmsv5

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 2f9b280a1323688c7ee925f351e85c9be974d02d
