database:
  driver: pdo_mysql
  user: cmsv4
  password: cmsv4
  dbname: cmsv4
  host: localhost

mail:
  use: swift_mailer
  php_mailer:
    charset: utf-8
    smtp_auth: true
    host:
    username:
    password:
    port: 587
  mandrill:
    api_key:
    template_name:
    template_content: []
    global_merge_vars:
      COMPANY: myCompany
      SENDERMAIL: sender@company.com
  swift_mailer:
    charset: utf-8
    smtp_auth: true
    host:
    username:
    password:
    port:

template:
  path: default
