database:
    driver: pdo_mysql
    user: cmsv4
    password: cmsv4
    dbname: db_test_install4
    host: localhost
mail:
    CharSet: utf-8
    SMTPAuth: true
    Host:
    Username:
    Password: 
    Port: 587
